## Libraries: Numpy
One of the advantages of using Python to process data is the ability to use libraries. Libraries are collections of modules that contain functions to be used by other programs (for example, our notebooks and scripts). These functions usually save us a lot of time when performing certain tasks, since we do not need to write our own code to carry them out.

In addition, libraries are usually developed following best practices:

Well designed code
They use version drivers
They have automated tests
Extensive documentation
Developed by a community
In this notebook we will explore one of the most used libraries when it comes to scientific computing: Numpy and Pandas.

### Importing libraries
In order to make use of the libraries, we first need to import them.

In [ ]:
import numpy

This allows us to access the modules and functions of the library. For example, Numpy offers us a function to calculate the mean of a series of values:

In [ ]:
numpy.mean([1, 2, 3, 4])

Many times it is tedious to write the entire library name every time we want to use its functions or modules. One option is to import them under an alias. For example, NumPy is usually imported under the name np.

In [ ]:
import numpy as np

np.mean([1, 2, 3, 4])

2.5

## Numpy Arrays
NumPy introduces a new type of variable, the numpy.array.

Like lists, they allow you to store many values under a single variable:

In [ ]:
evens = np.array([2, 4, 6, 8])
print(evens)
type(pares)

In [ ]:
temperature = np.array([10.1, 14.6, 18.3, 20.3])
print(temperature)

[10.1 14.6 18.3 20.3]


We can use indexes as we did with lists:

In [ ]:
temperature[0]

10.1

In [ ]:
temperature[2:]

array([18.3, 20.3])

### First Exercise
Using the temperature array above, index values to only include 10.1, 14.6 and 18.3.

In [ ]:
temperature[0:3]

array([10.1, 14.6, 18.3])

Note, we can also do mathematical operations on arrays. For example we can convert arrays from inches to centimeters:

In [ ]:
inches = [1,2,3,4,5,6,7]
inches = np.array(inches)
centimeters = inches * 2.54 #2.54 centimeters per inch
print(centimeters)

[ 2.54  5.08  7.62 10.16 12.7  15.24 17.78]


## Libraries: Pandas
Tha pandas library provides tools to create, import and edit dataframes within python. In this exercise, we will be going over how to create and store a dataframe. One way to create a dataframe is through a dictionary. Before we create the dataframe, we need to import the pandas package: 


In [ ]:
import pandas as pd

In [ ]:
Dictionary_Example = {'First Column': [1,2,3,4,5], 'Second Column': [10,11,12,13,14]}
df=pd.DataFrame(Dictionary_Example)
print(df)

   First Column  Second Column
0             1             10
1             2             11
2             3             12
3             4             13
4             5             14


## For pandas, should we import a da