# A conda environment for CoCo coding sessions.
#
# Usage:
#   $ conda env create --file=environment.yml
#   $ source activate coco

name: coco
channels:
  - defaults
  - conda-forge
dependencies:
  - python =3
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyterlab
  - rasterio
  - xarray
  - rioxarray
  - pip:
    - planetary computer
    - pystac_client
    - odc
